"""Add session family_id

Revision ID: ea2a7c12b5ca
Revises: 83162e50a75b
Create Date: 2026-09-21 15:06:13.223505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2a7c12b5ca'
down_revision = '83162e50a75b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_sessions_family_id'), ['family_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_family_id'))
        batch_op.drop_column('family_id')

    # ### end Alembic commands ###
